import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TopMatch from '../components/TopMatch'
import Bets from '../components/Bets'
import {
  BRAZIL_TOKEN_ABI,
  BRAZIL_TOKEN_ADDRESS,
  FRANCE_TOKEN_ADDRESS,
  FRANCE_TOKEN_ABI,
  SWAP_CONTRACT_ADDRESS,
  SWAP_CONTRACT_ABI,

} from "../constants"


import { useAccount, useContractWrite, usePrepareContractWrite } from 'wagmi';
import { useState, useRef } from 'react'

// import { useSigner } from 'wagmi'
import { ethers } from 'ethers'

export default function Home() {
  // const { data: signer, isError, isLoading } = useSigner();
  const { address } = useAccount();
  const [title, setTitle] = useState('')



  /***
   * Approve Function on BRA Tokens
   */
  const { config: brazilApproveConfig } = usePrepareContractWrite({
    address: BRAZIL_TOKEN_ADDRESS,
    abi: BRAZIL_TOKEN_ABI,
    functionName: "approve",
    args: [SWAP_CONTRACT_ADDRESS, 10000000]
  })
  const { write: brazilWrite } = useContractWrite(brazilApproveConfig);


  /***
 * Approve Function on FRA Tokens
 */
  const { config: franceApproveConfig } = usePrepareContractWrite({
    address: FRANCE_TOKEN_ADDRESS,
    abi: FRANCE_TOKEN_ABI,
    functionName: "approve",
    args: [SWAP_CONTRACT_ADDRESS, 10000000],

  })
  const { write: franceWrite } = useContractWrite({
    ...franceApproveConfig,
    onSuccess() {
      disableApproveBtn()
    }
  })


  /***
 * Call Deposit Function on BRA Tokens
 * 
 * default value is 0.002 Matic
 */


  /**
   * Disable Approve button when transaction is succesful
   */
  const ref = useRef(null);
  const disableApproveBtn = () => {
    ref.current.hidden = true;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Liquid bet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <button className={styles.approve} ref={ref} onClick={() => {
          brazilWrite()
          franceWrite()
        }}>
          Approve
        </button>
        <div className={styles.depositContainer}>
          <p>Deposit Matic to place Bets <br />(default 0.002MATIC)</p>
          <form>
            <input
              type='number'
              title="Amount of MATIC to deposit"
              placeholder='Enter MATIC amount to Deposit'
              onChange={e => setTitle(e.target.value)}
              value={title}
            />
            <button onClick={(e) => {
              e.preventDefault()
              depositWrite()
            }}>Deposit</button>
          </form>
        </div>

        <TopMatch />
        <Bets />

      </div>
    </div>
  )
}
