import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TopMatch from '../components/TopMatch'
import Bets from '../components/Bets'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Liquid bet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopMatch />
      <Bets />
    </div>

  )
}
